AWSTemplateFormatVersion: 2010-09-09
Description: event-manager-api

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  getEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-events.getEventsHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get all events from DynamoDB.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Environment:
        Variables:
          EVENTS_TABLE: !Ref EventsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /events
            Method: GET

  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-id.getByIdHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get one event by eventId from DynamoDB.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Environment:
        Variables:
          EVENTS_TABLE: !Ref EventsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /events/{id}
            Method: GET

  createEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-event.createEventHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Create a new event in DynamoDB.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Environment:
        Variables:
          EVENTS_TABLE: !Ref EventsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /events
            Method: POST

  updateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/update-event.updateEventHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Update an existing event in DynamoDB.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Environment:
        Variables:
          EVENTS_TABLE: !Ref EventsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /events/{id}
            Method: PUT

  deleteEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/delete-event.deleteEventHandler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Delete an event from DynamoDB.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Environment:
        Variables:
          EVENTS_TABLE: !Ref EventsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /events/{id}
            Method: DELETE

  EventsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: eventId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON